{% set version = "3.7.0" %}

package:
  name: openquake.engine
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/openquake.engine/openquake.engine-{{ version }}.tar.gz
  sha256: 5ce4254f7285f8f49406def79421c66f76ee263f00900b7d4896040f1362919f
  

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - h5py >=2.9
    - numpy >=1.16
    - scipy >=1.3
    - pyzmq <18.2
    - psutil >=2.0
    - shapely >=1.3
    - docutils >=0.11
    - decorator >=4.3
    - django >=1.11
    - matplotlib >=1.5
    - requests >=2.20
    - pyshp >=1.2.3
    - pyyaml
    - toml

test:
  imports:
    - openquake

about:
  home: https://github.com/gem/oq-engine
  license: GNU Affero GPL v3
  summary: 'Computes earthquake hazard and risk.'
  license_family: AGPL
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mhearne-usgs
    - cbworden
    - emthompson-usgs
