{% set version = "3.4.0" %}

package:
  name: openquake.engine
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/openquake.engine/openquake.engine-{{ version }}.tar.gz
  sha256: 4d3081c086c52eb61c65de8b2a3bb735608d5e11517b67cc6a0e66d98a1c001f
  

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - mock >=1.0
    - h5py >=2.8
    - numpy >=1.14
    - scipy >=1.0.1
    - rtree >=0.8.3
    - pyzmq <18.0
    - psutil >=2.0
    - shapely >=1.3
    - docutils >=0.11
    - decorator >=4.3
    - django >=1.10
    - matplotlib >=1.5
    - requests >=2.20
    - pyshp >=1.2.3
    - pyyaml
    - toml

test:
  imports:
    - openquake

about:
  home: https://github.com/gem/oq-engine
  license: GNU Affero GPL v3
  summary: 'Computes earthquake hazard and risk.'
  license_family: AGPL
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mhearne-usgs
    - cbworden
    - emthompson-usgs
