travis:
  secure:
    BINSTAR_TOKEN: GPmNGP2cclVXl/C6gd84cBwizc5bWjSbIkq1yQ9MdUYs5BFRA8K0ABjpPtjyD8gemt6+u1Pm8GI4S7XRaENkSUxb9qNklmrS5q5yNQF8COeZAmZWIXVzQM7KJBBGfgrDs69XnwC4NSig3QfO9a/FFvmr4GgU9EVwZ/rhdF+6pN7/c8Hb4cKCXQ4Vma6EUY0PadH4idERtt2dl3yvAwaZmJdesKAcZXFuRc2JJEVeuYuV3FMb76xRXGTKFuqrsM5F6EgjkL0v34WXLJKY7EDRdQs1OVffjVJUkXXQjeH6DvRAjwJL+KOvmhKyjIZOUOnJatrqadDyAmxYZHiDmmRqil3VSl7tTBpaRZnahDx6ZXUaDXPJUcBjIazPe0Q/mPbg2kcNfF0k5SKQw89ejvQbMu0on1aBwPlglIhTs1HdBxoaQ0Ikw3ZpvRfnQViiErYREsPOt5I01oOm239t+3lsmj6hW8GoJmwT8REQ2nLL/1XujPl4MvKTE5g29JH5JoTUkFlBFCLjY2J3DrPainVrNgjML0iWFrgN9lb/cNYmPDbcoPB6+SjawrH152dGPIB/WcOQ1V2cR5pMJhNZXDQnKALzx2T0oMLTJz4wY0p75LBqk+aNOqCjkjcE8RZtBEeuAPFhIdAb9xUwS7baw1XVeFAXYOCF5VqMhzwdicgTDtA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
