travis:
  secure:
    BINSTAR_TOKEN: Q6rfk0+VQK9GLIHMle9bfdeBLyKIiuwEJlpnZjfcjuI0n+rnvYkTZn6KJgEQJUW456OEYAzp0fHWK6+A6QzHg16ZtW7vUPaNcN8DrZpvyNed8QDW83PIw0IokdOvTzKTHY9T4TUiXtLEF8je4s+IWqpq1/NHaOfG23Fq+HgxNaL43iJs5w4b9P7PiOLEX2nQttn4765ULBBNzB+TJgjuso0t/ZIKPT2943H38MsdDdeUsPi2smeXbsMCqDtF1BLC7gQFHv0gfFHp7zDlHCNg2A2kU1KxPCPMOeW43A1IdVgYL5z64V4BypeKu/F2OYrD5GW7JDhlCvXl5RUxVZfsCGrBNdBcWMzP2CqtAK3LkO5i2wnvyWTsndcnaWHetLfXezkxgimIE+WXteCJy5rAtcjzDNqYo66QBzBV0IKbB9Mhfym7s8LeCwRZuH30h/tGnSpgh5s1u59L8ToDCWj9a1SoORTAjf4ttSlaOdAIkLB/c6q1KtvaCljrvHEjW+BHSX05+0ne3Z8/jTG3d2KLut1vE2DGga+T5PDvgOWgB9w8+TKH5o1OPpImHEfaDUOvCZVdURd7oWds1htHoFEsQmjXd5ofAA+X5bTqcQMLdrwGJlydb5d7TMU8yiqD9iJu307DPeY4PRMnFXunTUysCXTd9keafy9mYsP/0WkXXpk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
